# Generated by Django 4.2 on 2023-11-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_history_recyclestats_paper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='day',
            new_name='date',
        ),
    ]
